version: '3.1'
services:
  postgres:
    image: postgres:14.5-alpine
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: chat-tecsup
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdata: